### ISSUE TITLE
Pip package not working

### ISSUE THREAD

**Issue by willprice** [alexandrosstergiou/dataset2database#1]
Hi Alex :wave: 
Thought I'd try this approach out, but I had difficulty using the package on PyPI as it appears no source code is included.

**Comment by alexandrosstergiou** [comment]
Hey Will,
Thanks for letting me know! 
Should be working now after the latest commit [`#0658a55`](https://github.com/alexandrosstergiou/dataset2database/commit/0658a55c36a86411b18cbc10c59dc223223d4c56) and have a bit more support for other video formats. Let me know if you ran into any more bugs.

P.S. Also if you are to use it for PyTorch projects, there is a `torch.utils.data.Dataset` [class available](https://github.com/alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates/blob/master/data/video_iterator.py) that you can use as a plug-n-play :)

**Comment by willprice** [comment]
Great, thanks Alex. I look forward to testing this approach out this week :) thanks for the links to the dataloaders too, they should be helpful. Hope all is well at your end
