### ISSUE TITLE
Questions of creating destination directory

### ISSUE THREAD

**Issue by mzhou52** [alexandrosstergiou/dataset2database#2]
Hi, Alex. I have some questions about creating destination directory in jpgs2singlefile.py(line 97~99). 
I suppose the code intends to extend the destination directory with class name and video name (_dst_dir/class/video_) and store the data in it. Instead, the split path code here in line 99 will generate the path destination directory wrongly (_dst_dir/base_dir/class/video_). 

This will result in function `file2sql` can not find video path and so the frames will not be added into frames.db. 
If change the index from 1 to -2, the whole code will successfully run. That means the line 99 should be `name = os.path.join(*(name.split(os.path.sep)[-2:]))`

**Comment by alexandrosstergiou** [comment]
Hi @Blink621 ,

The `convert` function will create a new directory with structure: `<new_dataset_name>/<class_name>/<video_id>/<frames.db>`. This way you can keep the original video files as backups in their existing directory (and re-use the script, if the created directory becomes corrupted at any point).
e.g. for UCF-101 (on Ubuntu), `convert('UCF-101','UCF-101_videos')` will create a directory (if it does not exist) "UCF-101_videos" and will populate it with the corresponding `.db` files with video frames.

If I understand correctly, you are trying to add the new dataset directory within the original directory. This would require changing the current functionality with the change that you mentioned.  

So it all depends on which of the two functionalities is more preferable to you, and either use the current code, or make the change in line 99.

Best,
Alex

**Comment by mzhou52** [comment]
I totally understand what you mean now, thanks for your work!
