### ISSUE TITLE
n_frames file is missing?

### ISSUE THREAD

**Issue by dragen1860** [alexandrosstergiou/dataset2database#3]
dear author:
  I succeed to run your converter but found only *.db was created. Can not find n_frames files? thank you.

**Comment by alexandrosstergiou** [comment]
Hi @dragen1860,

This repository is for solely converting video files to `.db` format. If you're coming from Squeeze-and-Recursion-Temporal-Gates repo, you can generate the `n_frames` files with this script: https://github.com/alexandrosstergiou/Squeeze-and-Recursion-Temporal-Gates/blob/master/data/num_frames.py.

Best,
Alex
